spring.application.name=school-mgmt
spring.profiles.active=local

server.port=8090
# Common JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator Settings
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
